
ABOUT_SPIKEPY_TEXT = ("Spikepy is a python-based spike sorting "
            "framework. It has been designed to be general enough to implement "
            "many different spike sorting algorithms. Spikepy can be used by "
            "electrophysiologists without any additional programming required. "
            "Additionally, spikepy can be easily extended to include many more "
            "algorithms, or to mix and match aspects of any existing "
            "algorithms.")
OPEN_TEXT = "Open"
EXIT_TEXT = "Exit"
PREFERENCES_TEXT = "Preferences" 
WORKSPACES_TEXT = "Workspaces"
SHOW_TOOLBARS_MENU_TEXT = "Show toolbars on plots"
PYTHON_SHELL_MENU_TEXT = "Python shell"
ABOUT_TEXT = "About"
FILE_TEXT = "File"
EDIT_TEXT = "Edit"
VIEW_TEXT = "View"
HELP_TEXT = "Help"
SAVE_WORKSPACE_TEXT = "Save current workspace..."
FILE_NUM_TEXT = "Num"
FILENAME_TEXT = "Filename"
FILE_OPENING_STATUS_TEXT = "Opening"
OPEN_ANOTHER_FILE_TEXT = "Open Another File..."
OPEN_FILE_TEXT = "Open File..."
CLOSE_FILES_TEXT = "Close Files"
CLOSE_FILE_TEXT = "Close File"
ENTER_NEW_WORKSPACE_TEXT = "Enter a name for the new workspace:"
NEW_WORKSPACE_DLG_CAPTION_TEXT = "Save current workspace"
OPEN_FILE_DLG_MESSAGE_TEXT = "Choose file(s) to open."
TRACE_TEXT = "Trace"
SAMPLE_NUMBER_TEXT = "Sample Number"
TIME_AXIS_TEXT = "Time (ms fixme)"
SPIKE_RATE_AXIS_TEXT = "Estimated\nspike rate (Hz)"
DETECTION_TRACE_GRAPH_LABEL_TEXT = "Detection Filtered"
SPIKES_GRAPH_LABEL_TEXT = "Spikes"
RAW_TEXT = "Raw"
PSD_AXIS_TEXT = "PSD (dB/Hz)"
FILTERED_TRACE_GRAPH_LABEL = "Filtered"
