# To differentiate between the strings that only differ by case, consider 
# ending variable with sc, uc, lc for start case, upper case, and lower case.\

ABOUT_SPIKEPY = ("Spikepy is a python-based spike sorting "
            "framework. It has been designed to be general enough to implement "
            "many different spike sorting algorithms. Spikepy can be used by "
            "electrophysiologists without any additional programming required. "
            "Additionally, spikepy can be easily extended to include many more "
            "algorithms, or to mix and match aspects of any existing "
            "algorithms.")
OPEN = "Open"
EXIT = "Exit"
PREFERENCES = "Preferences" 
WORKSPACES = "Workspaces"
SHOW_TOOLBARS_MENU = "Show toolbars on plots"
PYTHON_SHELL_MENU = "Python shell"
ABOUT = "About"
FILE = "File"
EDIT = "Edit"
VIEW = "View"
HELP = "Help"
SAVE_WORKSPACE = "Save current workspace..."
FILE_NUM = "Num"
FILENAME = "Filename"
FILE_OPENING_STATUS = "Opening"
OPEN_ANOTHER_FILE = "Open Another File..."
OPEN_FILE = "Open File..."
CLOSE_FILES = "Close Files"
CLOSE_FILE = "Close File"
ENTER_NEW_WORKSPACE = "Enter a name for the new workspace:"
NEW_WORKSPACE_DLG_CAPTION = "Save current workspace"
OPEN_FILE_DLG_MESSAGE = "Choose file(s) to open."
TRACE = "Trace"
SAMPLE_NUMBER = "Sample Number"
PLOT_TIME = "Time (ms)"
TIME_AXIS = "Time (ms fixme)"
SPIKE_RATE_AXIS = "Estimated\nspike rate (Hz)"
DETECTION_TRACE_GRAPH_LABEL = "Detection Filtered"
SPIKES_GRAPH_LABEL = "Spikes"
RAW = "Raw"
PSD_AXIS = "PSD (dB/Hz)"
FILTERED_TRACE_GRAPH_LABEL = "Filtered"
MISSING_PLOT_ERROR = "Plot associated with '%s' does not exist."
ENLARGE_CANVAS = "Enlarge Canvas"
ENLARGE_FIGURE_CANVAS = "Enlarge Figure Canvas"
SHRINK_CANVAS = "Shrink Canvas"
SHRINK_FIGURE_CANVAS = "Shrink Figure Canvas"
DETECTION_FILTER = "Detection Filter"
DETECTION = "Spike Detection"
EXTRACTION_FILTER = "Extraction Filter"
EXTRACTION = "Extraction"
FEATURE_AMPLITUDE = "Feature Amplitude"
FEATURE_INDEX = "Feature Index"
EXTRACTED_FEATURE_SETS = "Extracted Feature Sets"
EXCLUDED_FEATURE_SETS = "Excluded Feature Sets"
CLUSTERING = "Clustering"
SHOW_CURSOR_POSITION = "Show cursor position"
USE_SCIENTIFIC_NOTATION = "Use scientific notation"
SETTINGS = "Settings"
MISSING_IMAGE_ERROR = "Cannot find image named %s in icons folder."
