#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

down_bar_arrow = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACMAAAAiCAYAAADVhWD8AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sDChYwCSIBjW0AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAIrElEQVRYw4WYyY9lyVXGf+dE"
    "3OENOVR1VWd2DV3dXd3qBmxZDCvDikEWC1ixQ16wQvwx/AU2WyQWLJGwoIVKsAAkMMbIpmW6"
    "jdvdVGZNObzp3hsR57B4+XKoymqHdPVuvBsn4ovvnIj4Toi7O2dl8+q+4quKSHOl/fo/Of8t"
    "ls6/i8jZN8d9/QStX7EDJb7cKYCddXK18QVgIeD+sp2waSpU629eADl7AMo1IC5KfHkgAJXm"
    "EkuvMuPXTGBdF9xBVTEDs7W9yGZyEXkNo1fAXAzuiMbz95cHFRGEjKq83o8ecAM3wd3RIIjo"
    "+cDu6dyFlwHFy5XN4CtfELQgzAmrJdXqBNJnpPKMRIPrIVmFab4FUkgWCK7k6hlOQ9JTxv6A"
    "PN+mmTSEnSnOfSS8Q86gGul1RaUNsQRwY4j5qps2wMbdBNUlvjognf6AIf8I50f0/RO6pbAT"
    "GrR0qEVgoEGBmkgP2lCqiKgSS0WX3qSs3obwPqPtb1DtPIC8g4hSHKIDIiiKbFbThhV3J5RE"
    "OXlEf/iINP8fgsyomkQtAbGa3FZYNwPpEROiBiRWeC9IdEgTKP8HVc8y7rDIU8SnNDsfsnXv"
    "tyH+GkOckByaYkSNFOVVZgD65WNmz/4RPfmYqQZUb9MtdnEvtNWCZCfI0hhu3MHre1QhYrKE"
    "5TPa/ktyK4QuUYWAW6CyOTF9jj1fUML7yN57hLhFEnDJa4/4JTAichGsx58gpz+h7p5Tt9sQ"
    "ThHrMevJHFDN9ol5G3379+HGb1FpoPdD/OQRHB/hZFI3wYEQIiOZoHbCYvmYvvyAMP6AenQf"
    "FfCQwWrMXmJmE8jN4b8jiyOq/iZ0LVa/oGm2COEmOTtJVgSHfvIuvv2QwSDpHs3O9xmOBsYn"
    "DVl2Kf0x0eYoIwhvgB3Qn/wz1eybNDcMrxU42yDLa9zkjw+QIEi4C9ow5BWEhkHvMR8Sk/ox"
    "Uk5o2KU42HKgmo4YByMN0PGUsvOAJAPt/GfEJVi1S6i2afsO61+AFwQFrnHTFYbic5I+JtW7"
    "SLhFbxNi/YDR9m9SjSccHf41bTgh1i1BMiZHZG4BHcuuZ/TOt6j2/ghJnxIf/yXevWBVhBim"
    "xOWMzAoEFPANGFvXr6EmU3PKkANdWqLDEcIDwrt/QNn7Fm/e+xNm2++hQ0eg42QCQqCku9hb"
    "vwsP/5hu7z7N9jcZhgZbBmp9SllFvH1MmK/wWlAGmrwH2hOa1zCTM5ShZhQVCYXgI5IDcgrT"
    "fbrJPUT/FB/fR46EcQDfXpB2f53RzfeQ9h5BIlqWkA3XHq0yIQn5eEx86/rd+3owCXw1ZTSK"
    "wBIkkIcZ88WPkWkFusd4/yFJA5jRxDHZDW+ntKN3KBoZFp9Tjr9P6I6wIlhqCSlSFgF3OYuX"
    "l8BcPiPOYyY7OmxBE8nplEiE1ZecPv4HRmXO9MbvUdWFXgbyBGCEpkSQGnMhLFb0X/w98uQR"
    "bXdIznfoTjONZeqQcLsUEQKOv56ZaBm3CrSis8wEQ/oD5OAQOT4hfLhPufF1aA+I6Ra5zLF6"
    "oIl30fS/8MU/Eb78HvH4v9AuE0vAsxJ0QHGKCZi8ErHXnk1uK2CADNla0ELsV0zSjNYd9Dss"
    "3/021e2vU1e7dDpjUMWHJ2x99jf0n/8tk9ND4lIgjdFqyQinduhXgWAXGscBw9DXMVN8jg+n"
    "yOImtd9EWGK9oDGieY589q+wHFPtG+Wj36Bqd4iHn+CP/wo++Tes+zlNnsCwu5YKIRFSOdvc"
    "5ExaAK7ngsxfB8YYKGmJmFPrFmDkVCijluKCVXdof/zfhIM/J2//Ge2t30E//Zjlp99jOIWo"
    "O3geMaQlVhUagzRzYshELWsl+ZJoc/dXwZRSiKvbSL+i3noCoxFDWvDUGxg/ZFBnfHoMo4rc"
    "R/j4L1jxXdyEwi2G4HhYkdu7RBw//iGtC9XuDstZQlZzxE4oBiaK6JxgU5KnCw18Rf41EbJi"
    "RwM2H9CRsXP3A8a/8oeE6R2G8VtrxacKKCbrPoKfnW2LQyw7/vSHLP/jC2R2SGVzKhugmtFV"
    "LRLWcpSzlaSq12vgVVXjITLOggw9Q3TyaJfuza/hu79MpQvWzj6TjSi4E876STtvE1kiegjj"
    "CfZcUIucVLAcT9httxB1gmVAcYEo8qqb3J3V7m382RPiaolkoyTHO0dzT/Ce4JNzvS8b0e5n"
    "eYDAUqHkTO6NLiltt6KxRNCAjhqs2cYoBHUgUAClvObUHr1LV/0cGRZMLDK2QDx8TvzPR8jo"
    "X0hNQURQBxcD802yggMtNWUI8PQLprOeRgKIYz5Bwh7W3KJQCAhIxLzAdWBEhHb7lximP6Nf"
    "rahlSWNG/fSAPP87LD2hlnCJlw01tukA4QgtbxBtC4kZ4jYuDYv6DnnrG4yn+5jLehIhUqSA"
    "levFVfvgV+nmh5ymxPDip7Q6I5CIdQctDENzlin6q2AAq96gHmq8KwwBOq9gtEW4cZfdhx9R"
    "b98haYShA92Ma1dTlU1Z7L5JuPsh2s0YdMWChFuH1w1jv0lFOgNzKfDlAszCptTZ0eRYXXNU"
    "Inl8n7T/EeWdr/HW5AYZBfN1Zrph1Mz8sgY2MxYh4LMXpMOfMnz5CeXgJ+jJ58ThmMp7Qrmc"
    "Q1/YblZjsoKEllRNKe0t0s17hLsf0N5/n+b2PmPfObe/TMS1YLrQYaVgq57l7JTl6YzZ7IRV"
    "35FzZiHxlY6u5OxtwvtE7c7ueMre7X1u3rhFPR6DBry05/aq+tVgKN3ZaomAkouQXMgIRYRp"
    "8JduHi5ycncnIJSUKZbWm1lcp7YpGzln4qg6B3KF4evA9EERjOCGWkHcCeLrI1+Ezvqr9F5O"
    "cwDzhGoF1BSUArgFokYioDmf77q/EMwQFEEIl24czGyt5kzYjuEr729chGJrm4KjGGoQWR+Q"
    "pYq/OGYAzAwtZw1Url6vbA5TK6+9YwHQoutZiGNBcN1kAestIHh9rf3/Ax+F6lPfHVPgAAAA"
    "AElFTkSuQmCC")
getdown_bar_arrowData = down_bar_arrow.GetData
getdown_bar_arrowImage = down_bar_arrow.GetImage
getdown_bar_arrowBitmap = down_bar_arrow.GetBitmap

