#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

span_zoom = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABsAAAAZCAIAAABPfsIJAAAAAXNSR0IArs4c6QAAAAlwSFlz"
    "AAAOxAAADsQBlSsOGwAAAAd0SU1FB9sCEAc4BmVHTfgAAAAZdEVYdENvbW1lbnQAQ3JlYXRl"
    "ZCB3aXRoIEdJTVBXgQ4XAAAEhklEQVRIx61VS2xUZRQ+57/3zr1z7wwzczsjLSOIPGZCQQEr"
    "C0xAFIqyMBjihp0ao9HIAhI1cSFqmrggFBJ8JGIiLlj5SHwsTNCFmECh4VHSFCq0NC3TTKed"
    "R+dxX//LxUhfKSyEs/z/nO//vnO+8x+UUsJDDQIPO9QHhygO9lTPHBOUrT74IwDgA6oePf2e"
    "Jqr25mdqt3pZrKP1udf+v+pCzw8jJ15pWbO65akO6Q2HE0717y/vp3owNy3u0ieI2XRs5qo8"
    "PlT5tSva2rasc6/08ryaE07ODZIYSS+OODBaoSIYKhUCQJCASHQULqWpiJ5ORnO/HeXjV1q3"
    "7laII2r/CPcOpbRyW8P4srWHvlqkjtdGKjfLeUXXU5EQkcCF4EIAYNGlNkGz51RmechasVI4"
    "OeHmuJdv1Jc27lSX7DyQzD7dRJiH2D9a7pvIpRKxFkMjiEICE4IJ7nNGBa/7oBduZ8d/Xp6J"
    "cjcXuH55GI1M57Jdr8/lNIt4fazcP5WPRcyBmhszDIJESkE5Dzj3GfMoZYLbqtY+cmY9/nGr"
    "HKl71uiWN5mVBIBawN7fsm6hHwMWqIa+RNcs19+RXqqqCufcYzRg3GPMozRgbKLheNk9E71j"
    "T2x7OZrdDgASJAJ+PTC80OE3xiq3SpMtdgxAAiAADJeuKRhKmY/PVRTV1XI9yO79LNqiDxb7"
    "FaKsSTSpyYWIjDMfUDDKQaVceMw7eelwrZYQ5ZcCzoUUAoRH2bPrV2VakwgIACevdgvJu3d9"
    "16zeIlMopeSSM0GmvfyRcx8WGmNbH9u874XdlHOfsYAxn7GAs2LNRQQAMDXrwvhfh/58tWv7"
    "5zPyZxElSAQQAkYbg9cLPxWcIQAYGJsevnmWCU45b+JuWtXW3ra0mRJWTUKUoekb3/QdD8g2"
    "hNXzOKqIOkqXVc+Nfz/pXjY0M2BeLMzaH434zKOCB9x1mUPUYj3gBccwQkadVsMhMxaOnxn5"
    "Jb2k0gg6rFD0P/c0CZ+/OXLs2jt1OmGGLMuINvya67mUi2aFBDIEiaioqBIkiKAqatyyY6Y9"
    "WctXGsWMvaG789SsH6/ke764eLTgj0aNmBWyEImQggsmBAdAQogTNEr1qbhpW0ZUCgEgVUXT"
    "VUNRVMZpxSnXvOlMYt1bHR/MdsYIqeADQVSVkKqolFMhuZzbxXmBQgrKKRNMSjl38GZVe8w9"
    "8Pv+vDNuW0k7mirVJitOOQgoIgIAByqlUImmkhkS0tDNcMisu1UncNqTG492frtwrite6fjF"
    "Ty9PnLetZKkx9WTLjn1r3/W5CyDDIcrktG0kVaIpRCVATlzq6pvs1VTdD9wV8Z3dOw83OzPX"
    "PRg37P3tbwxV3FLjqk+9EtUulLy7unWARxARgQMIAJhwFcopF3xlfFdbbE8TbhaxaU4JMpvc"
    "cOT5jz45e3CofCOTCL29ce29vuQ7JTJWgfbUpq4dH5taZMbh87ZC86g1kj7x4ul0dIUT1O+z"
    "FRxaX5/a3N15ytQiM7mL/LgzTw1M9RmKsSqRvefaKPYrqKyx183NAoB/AYzugN8hoGD+AAAA"
    "AElFTkSuQmCC")
getspan_zoomData = span_zoom.GetData
getspan_zoomImage = span_zoom.GetImage
getspan_zoomBitmap = span_zoom.GetBitmap

